server:
  port: 6061 # port on which eureka server will be available

spring:
  application:
    name: nflix-eureka-server # name of eureka server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:6061/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF