
server:
  port: 9091

spring:
  application:
    name: ms-commands
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:commands
    driver-class-name: org.h2.Driver
    name: commandsdb
    username: sa
    password:

eureka: # EUREKA
  client:
    serviceUrl:
      defaultZone: http://localhost:6061/eureka/

info:
  app:
    name: ms-commands
    description: microservice responsable de la gestion des commandes
    version: 0.1.0