
server:
  port: 8080

spring:
  application: # Identity
    name: ms-clientui

eureka: # Eureka
  client:
    serviceUrl:
      defaultZone: http://localhost:6061/eureka/

ms-products:
  ribbon:
    listOfServers: http://localhost:7071,http://localhost:7072