#server:port: 9090
spring:
  application:
    name: ms-products
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:productdb
    driver-class-name: org.h2.Driver
    name: productdb
    username: sa
    password:

eureka: # EUREKA
  client:
    serviceUrl:
      defaultZone: http://localhost:6061/eureka/

info:
  app:
    name: ms-products
    description: microservice responsable de la gestion des produits
    version: 0.1.0

config: # Nos configurations
  products:
    limit: 3
