
server:
  port: 9092

spring:
  application:
    name: ms-paiement
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:paimentdb
    driver-class-name: org.h2.Driver
    name: paimentdb
    username: sa
    password:

eureka: # EUREKA
  client:
    serviceUrl:
      defaultZone: http://localhost:6061/eureka/

info:
  app:
    name: ms-paiement
    description: microservice responsable des paiements
    version: 0.1.0